### PR TITLE
Efficient algorithms for column and row splitting

### PR DESCRIPTION
**Pull request by fedelux3**
Adding some methods for column and row splitting for the structural learning algorithm LearnSPN:

Column splitting:
- RGVS (Random Greedy Variable Splitting)
- WRGVS (Wiser Random Greedy Variable Splitting)
- EBVS (Entropy Based Variable Splitting)
- EBVS-AE (Entropy Based Variable Splitting - Adaptive Entropy)
- GBVS (Gini Based Variable Splitting)
- GBVS-AG (Gini Based Variable Splitting - Adaptive Gini)

Row splitting:
- K-means MiniBatch
- DBSCAN
- Wald

The reference for some column splitting methods is: 
Nicola Di Mauro, Floriana Esposito, Fabrizio Ventola, and Antonio Vergari.Sum-product network structure learning by efficient product nodes discovery.Intelligenza Artificiale, 12:143–159, 01 2019
https://www.researchgate.net/publication/330723826_Sum-Product_Network_structure_learning_by_efficient_product_nodes_discovery

### CODE REVIEW

**Review by loreloc — COMMENTED** [review]
Thank you!

Please follow [reStructuredText](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html) format for methods documentation. That is, use `"""` instead of `'''` to denote a documentation block, use :param:, :return: in parameters and returns specifications, and start each sentence with an uppercase and end it with a punctuation. You might test the generated documentation by using Sphinx and executing the Makefile in `docs` folder.

Also, in the library we often refer to the Laplace smoothing factor as `alpha`, so it is preferred to use that instead of simply `a`.
Finally, consider using [scipy.stats.entropy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.entropy.html) to compute the entropy of a distribution.
Moreover, consider moving the computation of Gini statistic for discrete data to **deeprob.utils.statistics** module for future usage.

**Comment by fedelux3** [comment]
Thank you for the reply.

I've written the comments following the reStructuredText format. Also, I've substituted the ``a`` reference with ``alpha``. 

I've considered using scipy.stats.entropy but in that particular implementation, no Laplace smoothing parameter can be used so it may cause problems in some situations therefore I've preferred to maintain the handmade function. 
Finally, the Gini and Entropy statistics computations have been moved to __deeprob.utils.statistics__ for future usage.  To avoid some import warnings, few changes have been made.

I remain available for any clarification

**Review by fedelux3 — COMMENTED** [review]
Thank you for the reply.

I've written the comments following the reStructuredText format. Also, I've substituted the ``a`` reference with ``alpha``. 

I've considered using scipy.stats.entropy but in that particular implementation, no Laplace smoothing parameter can be used so it may cause problems in some situations therefore I've preferred to maintain the handmade function. 
Finally, the Gini and Entropy statistics computations have been moved to __deeprob.utils.statistics__ for future usage.  To avoid some import warnings, few changes have been made.

I remain available for any clarification

**Review by loreloc — COMMENTED** [review]
Some other issues:
- In **spn.learning.splitting.cluster** fix comments at lines 120-122, 152-154.
- Remove trailing whitespaces at lines 70, 134, 141-142, 209 in **spn.learning.splitting.gvs**.
- Remove assertions for debugging reasons.
- **np.int** is [deprecated](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations), use np.int64 instead.
- **np.histogram** already returns a pair of `np.ndarray`, no need to call `np.array(hist)`.

Another thing: both **compute_entropy** and **compute_gini** are preferred to work on a single feature, rather than having the whole data and a feature index as inputs. This should improve code reusability. Moreover, I think the Laplace correction in both of them is incorrect:
`probs = smoth_freq / (data.shape[0] + (domains[idx] * alpha))`
`probs = smoth_freq / (data.shape[0] + (bin_edges[1:] * alpha))`
should be:
`probs = smoth_freq / (data.shape[0] + (len(domains[idx]) * alpha))`
`probs = smoth_freq / (data.shape[0] + ((len(bin_edges) - 1) * alpha))`

**Pull request merged**
